# Display
FF "COMMON_CONFIG_MDNIE_MODE" "62481"

# High Performance Mode
FF "COMMON_SUPPORT_HIGH_PERFORMANCE_MODE" "TRUE"
FF "SYSTEM_SUPPORT_ENHANCED_CPU_RESPONSIVENESS" "TRUE"

# Enable Video brightness feature
FF "COMMON_SUPPORT_HDR_EFFECT" "TRUE"

# Enable Extra Brightness feature
FF "LCD_SUPPORT_EXTRA_BRIGHTNESS" "TRUE"

# Saiv
FF "SAIV_CONFIG_AI_REVITAL_VERSION" "1.7,1"